skyflowapi/skyflow-react-js

README.md, samples/SkyflowElements/src/components/CollectElements/index.tsx, samples/SkyflowElements/src/components/ElementListeners/index.tsx, src/elements/InputField/index.tsx, src/index.ts, tests/elements/InputFieldElement.test.tsx, tests/elements/__snapshots__/InputFieldElement.test.tsx.snap
=> SDK-711/ Add custom input field element

package.json
=> SDK-700/ Add description for react sdk

README.md, samples/SkyflowElements/src/components/CustomValidations/index.tsx, src/index.ts
=> SDK-715/ Remove Element Match Rule from readme

CHANGELOG.md, package.json, samples/SkyflowElements/package.json
=> SDK-719/ Update versions and Changelog

README.md, src/elements/index.ts, src/hooks/CollectContainer/index.ts, src/hooks/CollectListner/index.ts, src/hooks/RevealContainer/index.ts, tests/elements/CVVElement.test.tsx, tests/elements/CardHolderNameElement.test.tsx, tests/elements/CardNumberElement.test.tsx, tests/elements/ExpirationDateElement.test.tsx, tests/elements/ExpirationMonthElement.test.tsx, tests/elements/ExpirationYearElement.test.tsx, tests/elements/InputFieldElement.test.tsx, tests/elements/PinElement.test.tsx, tests/elements/RevealElement.test.tsx
=> SDK-749/Update README for collect options

package.json
=> SDK-754/ Update JS SDK version to make patch release

CHANGELOG.md
=> SDK-755/ Update changelog for patch release 23.09.2022

CHANGELOG.md, README.md, package.json
=> SK-51/ Upsert support in React SDK

README.md
=> SK-170/ Revert upsert changes in README

CHANGELOG.md
Changelog file updated for React-SDK
=> SK-660: Changelog update ReactJS

src/core/hook.ts, tsconfig.json, typings.d.ts
=> SK-705: add-metrics-to-react-sdk

package.json, src/elements/FileRenderElement/index.tsx, src/elements/RevealElement/index.tsx, src/hooks/UpdateElement/index.ts, src/hooks/UpdateFileRenderElement/index.ts, src/hooks/UpdateRevealElement/index.ts, tests/hooks/useUpdateElement.test.ts, tests/hooks/useUpdateFileRenderElement.test.ts, tests/hooks/useUpdateRevealElement.test.ts
- SK-1287 Update Collect Element props dynamically
- SK-1288 Update Reveal & File Render Element props dynamically
=> SK-1286 ability to update element props dynamically

.github/workflows/CI.yml, .github/workflows/codeql-analysis.yml, .github/workflows/main.yml, .github/workflows/release.yml, README.md, samples/SkyflowElements/README.md
To change default branch as main from master.
Made changes to workflow files to change the branch from master to main
=> SK-1572 update master to main branch as default

.semgreprules/customRule.yml
Implementing Semgrep to this repository
=> SC-3122:Create customRule.yml

.github/workflows/semgrep.yml
Implementing semgrep for this repository
=> SC-3122:Create semgrep.yml

package-lock.json, package.json, src/hooks/CollectContainer/index.ts, src/hooks/RevealContainer/index.ts
- Having a RUM solution for tracking iframe events.
- To track iframe performance and loads
- Have done manual testing of the feature under different scenarios like low latency mode
=> SK-1626: coralogix iframe metrics

package-lock.json
**Why**  
The current Skyflow React.js project contains a few vulnerabilities that could lead to potential issues, such as security risks.  
**Goal**  
Enhance security by addressing the identified vulnerabilities.
=> SK-1807: Fix vulnerabilities

README.md, samples/SkyflowElements/src/App.tsx, samples/SkyflowElements/src/components/CardBrandChoice/index.tsx
**Why**
For every feature release, we
- update README with proper instructions and guidelines about the feature
- provide a sample to help users get started with the new feature
**Outcome**
- User will know about the newly released updates and their instructions and guidelines
- User can update vault and other required details to use this sample code for card brand choice.
=> SK-1837: Update README and added sample for card brand choice

package-lock.json, package.json
=> SK-1511: iframe versioning

package.json, samples/SkyflowElements/src/App.tsx, samples/SkyflowElements/src/components/3DSHelperFunctions/index.tsx, src/hooks/ThreeDS/index.ts, src/index.ts, tests/hooks/use3DS.test.ts
=> FINT-664:3DS get browser details helper 

package.json, samples/SkyflowElements/src/App.tsx, samples/SkyflowElements/src/components/3DSHelperFunctions/index.tsx, src/hooks/ThreeDS/index.ts, src/index.ts, tests/hooks/use3DS.test.ts
=> FINT-664:3DS get browser details helper

package-lock.json, package.json
=> SK-1925: update js version

package-lock.json, package.json, samples/SkyflowElements/src/App.tsx
- to fix setting iframe height to 0px
=> SK-1925: fix iframe resize

src/elements/CVV/index.tsx, src/elements/CardHolderName/index.tsx, src/elements/CardNumber/index.tsx, src/elements/ExpirationDate/index.tsx, src/elements/ExpirationMonth/index.tsx, src/elements/ExpirationYear/index.tsx, src/elements/FileInputElement/index.tsx, src/elements/InputField/index.tsx, src/elements/PIN/index.tsx, src/elements/index.ts
=> SK-1943 override custom error with ref

CHANGELOG.md, package.json, samples/SkyflowElements/package.json
This PR bumps JS SDK dependency version to support card brand choice enhancements in React SDK.
- The card brand choice behaviour required some enhancements.
- Now, the card icon for first option provided in scheme will be rendered in UI.
- This gives the flexibility to control the overall UX of card brand choice selection to the users.
- Tested the changes manually
=> SK-1982 Card brand choice enhancements

package-lock.json, src/elements/index.ts
- Masking support for collect element's input
- Input should be masked for collect elements when masking is set to true in collect element options
- User should be able to also provide custom masking character
=> SK-1851 update js version to support masking

README.md, package.json, samples/SkyflowElements/package.json, samples/SkyflowElements/src/App.tsx, samples/SkyflowElements/src/components/Masking/index.tsx
- To guide users on how to mask collect element's input
=> SK-1853 README and sample for masking

package-lock.json, package.json
Stalled headless iframes consume unnecessary system memory.
Single client-level headless iframe during Skyflow client instantiation.
Eliminated redundant headless iframes created by collect, reveal, and composable containers.
=> SK-2078 update js latest version for iframe refactoring

package-lock.json, package.json, samples/SkyflowElements/package.json
**Why**
- Dependabot has flagged a few vulnerabilities in the React SDK dependencies. These issues pose potential risks to the security and stability of the codebase.
**Outcome**
- This PR addresses and resolves the identified vulnerabilities, ensuring enhanced security and improved stability for the React SDK.
=> SK-2210 fix vulnerabilities
